const userDB = [
  {
    id: 1,
    firstName: 'Robert',
    lastName: 'Ndirangu',
    location: '23 Prairie Rose Road',
    email: 'robakadi@gmail.com',
    password: '89Ts2JDxz12',
    status: 'unverified',
    isAdmin: false,
  },
  {
    id: 2,
    firstName: 'Jessica',
    lastName: 'Teta',
    location: '2 Pepper Wood Pass',
    email: 'kaveray1@mail.ru',
    password: 'x6vG1vvLLY',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 3,
    firstName: 'kelvin',
    lastName: 'Munene',
    location: '56 Mallard Street',
    email: 'kevomwas21@gmail.com',
    password: 'hvHpTT7WZ',
    status: 'unverified',
    isAdmin: true,
  },
  {
    id: 4,
    firstName: 'Caryl',
    lastName: 'Bes',
    location: '70009 Hayes Court',
    email: 'cbes3@bloglines.com',
    password: 'mp8hTHu8G',
    status: 'verified',
    isAdmin: true,
  },
  {
    id: 5,
    firstName: 'Gianina',
    lastName: 'Corley',
    location: '4 Chinook Park',
    email: 'gcorley4@admin.ch',
    password: 'fpDgEhjlbw',
    status: 'verified',
    isAdmin: true,
  },
  {
    id: 6,
    firstName: 'Chaim',
    lastName: 'Wye',
    location: '1 Charing Cross Crossing',
    email: 'cwye5@youtu.be',
    password: '12HF36Yz6',
    status: 'unverified',
    isAdmin: false,
  },
  {
    id: 7,
    firstName: 'Torrey',
    lastName: 'Melluish',
    location: '42803 Mccormick Place',
    email: 'tmelluish6@freewebs.com',
    password: '7u0mmcz',
    status: 'unverified',
    isAdmin: false,
  },
  {
    id: 8,
    firstName: 'Tonye',
    lastName: 'Rowbury',
    location: '51526 Golf Course Park',
    email: 'trowbury7@indiatimes.com',
    password: 'n3rPorhB0JNP',
    status: 'verified',
    isAdmin: false,
  },
  {
    id: 9,
    firstName: 'Rebbecca',
    lastName: 'Kalberer',
    location: '9927 Cardinal Lane',
    email: 'rkalberer8@gravatar.com',
    password: 'XkHy4zuGbr',
    status: 'verified',
    isAdmin: true,
  },
  {
    id: 10,
    firstName: 'Gerty',
    lastName: 'Signe',
    location: '59 Eastwood Road',
    email: 'gsigne9@bloglovin.com',
    password: 'uSGvzfr',
    status: 'unverified',
    isAdmin: false,
  },
  {
    id: 11,
    firstName: 'Itachi',
    lastName: 'uchiha',
    email: 'uchiha.itachi@anbu.org',
    location: 'Hidden-leaf village, Konoha',
    password: 'secret',
    status: 'unverified',
    isAdmin: false,
  },
  {
    id: 12,
    firstName: 'Desmond',
    lastName: 'Edem',
    email: 'meetdesmond.edem@gmail.com',
    password: 'admin',
    location: '12 McNeil Street, Sabo-Yaba, Lagos',
    status: 'verified',
    isAdmin: true,
  },
];

export default userDB;
